mkdir: scraped_pages: File exists
Traceback (most recent call last):
  File "scrape.py", line 109, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "scrape.py", line 52, in main
    await page.goto('http://movielens.org/login')
  File "/usr/local/lib/python3.8/site-packages/pyppeteer/page.py", line 837, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.
